/**
 * Packaging entry for the single Windows .exe.
 *
 * Imports the shared `runCli()` from `../src/index.ts` (so esbuild bundles the
 * whole library + `@sentropic/cowork-bridge` + `@sentropic/chat-ui` into one
 * self-contained CJS file) AND the embedded native payload generated by
 * `package-windows.mjs` (`../build/native-payload.generated.mjs`). The payload is
 * a gzip+base64 string bundled into the exe; at first run the binary extracts it
 * to a real on-disk cache and resolves the native `.node`/DLLs from there.
 *
 * Behaviorally identical to `bin/cowork.mjs` (both call `runCli`); the only extra
 * step here is registering the embedded payload before running.
 */

import { runCli, registerNativePayload } from '../src/index.ts';
import nativePayload from '../build/native-payload.generated.mjs';

registerNativePayload(nativePayload);

runCli().catch((error) => {
    process.stderr.write(`fatal: ${error?.message ?? error}\n`);
    process.exitCode = 1;
});
