apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 10-rbac.yaml
  - 15-networkpolicy.yaml
  - 20-postgres.yaml
  - 30-api.yaml
  - 35-auth-idp.yaml
  - 40-ui.yaml
  - 70-pgbackup-cronjob.yaml
