import type { AuthUiBranding, AuthUiLabels } from './types.js';

export const createDefaultAuthUiLabels = (overrides: Partial<AuthUiLabels> = {}): AuthUiLabels => ({
  loading: 'Loading...',
  save: 'Save',
  cancel: 'Cancel',
  emailPlaceholder: 'you@example.com',
  webauthnRegisterNotice: 'You are about to register a new WebAuthn device. We will send you a confirmation email.',
  verifyInProgress: 'Verification in progress...',
  redirectingDashboard: 'Redirecting to your dashboard...',
  registerDeviceNow: 'You will now register your WebAuthn device.',
  loginTitle: 'Sign in',
  loginSupportedHint: 'Use a passkey to continue.',
  loginUnavailable: 'Passkeys are not available in this browser.',
  loginUnsupportedBrowser: 'Your browser does not support WebAuthn. Use a modern browser (Chrome, Firefox, Safari, Edge).',
  loginButton: 'Sign in with passkey',
  loginButtonLoading: 'Signing in...',
  loginLostDevice: 'Lost your device?',
  loginLostDeviceTitle: 'Lost device',
  loginNoAccount: "Don't have an account? Sign up",
  loginRegisterNewDevice: 'Register a new device',
  loginBackToLogin: 'Back to sign in',
  registerTitle: 'Create an account',
  registerSubtitle: 'Secure authentication with WebAuthn.',
  registerUnsupportedBrowserTitle: 'Browser not supported',
  registerUnsupportedBrowser: 'Your browser does not support WebAuthn. Use a modern browser (Chrome, Firefox, Safari, Edge).',
  registerEmailLabel: 'Email',
  registerGetCode: 'Get verification code',
  registerSendingCode: 'Sending code...',
  registerAlreadyHaveAccount: 'Already have an account? Sign in',
  registerCodeLabel: 'Verification code',
  registerCodeHelp: 'Enter the 6-digit code we just emailed you.',
  registerVerifyCode: 'Verify code',
  registerVerifyingCode: 'Verifying...',
  registerChangeEmail: 'Change email',
  registerCodeVerifiedTitle: 'Code verified',
  registerPasskeyButton: 'Register my WebAuthn device',
  registerRegistering: 'Registering...',
  registerSuccessTitle: 'Account created',
  registerSuccessCodeSent: 'Verification code sent by email.',
  registerSuccessRedirecting: 'Account created. Redirecting...',
  registerErrorInvalidEmail: 'Please enter a valid email address.',
  registerErrorSendCode: 'Failed to send the verification code.',
  magicLinkTitle: 'Verifying magic link',
  magicLinkVerifying: 'Verifying your link...',
  magicLinkSuccess: 'You are signed in.',
  magicLinkSuccessTitle: 'Signed in.',
  magicLinkErrorTitle: 'Verification failed',
  magicLinkBackToLogin: 'Back to sign in',
  magicLinkErrorMissingToken: 'Token missing from the URL.',
  magicLinkErrorVerifyFailed: 'Failed to verify the magic link.',
  devicesTitle: 'My devices',
  devicesSubtitle: 'Manage WebAuthn devices registered for this account.',
  devicesEmpty: 'No devices registered yet.',
  devicesRegister: 'Register a device',
  devicesAddNew: 'Add a new device',
  devicesRename: 'Rename',
  devicesRevoke: 'Revoke',
  devicesUvEnabled: 'UV enabled',
  devicesAddedOn: 'Added on {date}',
  devicesLastUsed: 'Last used: {date}',
  devicesConfirmRevoke: 'Are you sure you want to revoke the device "{deviceName}"? You will no longer be able to sign in with it.',
  devicesErrorLoad: 'Failed to load devices.',
  devicesErrorUpdate: 'Update failed.',
  devicesErrorRevoke: 'Revoke failed.',
  devicePairTitle: 'Pair a device',
  devicePairSubtitle: 'Enter the code displayed by the companion app on your workstation.',
  devicePairCodeLabel: 'Pairing code',
  devicePairCodePlaceholder: 'PAIR-XXXX',
  devicePairDeviceNameLabel: 'Device name',
  devicePairDeviceNamePlaceholder: 'My workstation',
  devicePairConfirm: 'Pair device',
  devicePairConfirming: 'Pairing...',
  devicePairSuccess: 'Device paired. You can return to the companion app.',
  devicePairBack: 'Back to devices',
  devicePairErrorCodeRequired: 'The pairing code is required.',
  devicePairErrorNotFound: 'Invalid or expired code.',
  devicePairErrorGeneric: 'Failed to pair the device.',
  passkeyNotSupported: 'WebAuthn is not supported in this browser',
  passkeyCancelled: 'Passkey operation cancelled by user',
  passkeyAlreadyRegistered: 'This authenticator is already registered',
  passkeyNoMatchingAuthenticator: 'No matching authenticator found',
  passkeyAuthenticatorNotSupported: 'This authenticator is not supported',
  passkeyRegistrationCancelled: 'You cancelled the registration.',
  passkeyAuthenticationCancelled: 'You cancelled the authentication.',
  ...overrides,
});

export const createFrenchAuthUiLabels = (overrides: Partial<AuthUiLabels> = {}): AuthUiLabels =>
  createDefaultAuthUiLabels({
    loading: 'Chargement…',
    save: 'Enregistrer',
    cancel: 'Annuler',
    emailPlaceholder: 'vous@example.com',
    webauthnRegisterNotice: "Vous allez enregistrer un nouvel appareil WebAuthn. Nous vous enverrons un email de confirmation.",
    verifyInProgress: 'Vérification en cours…',
    redirectingDashboard: 'Redirection vers le tableau de bord…',
    registerDeviceNow: 'Vous allez maintenant enregistrer votre appareil WebAuthn',
    loginTitle: 'Connexion',
    loginSupportedHint: 'Utilisez votre passkey ou biométrie',
    loginUnavailable: 'WebAuthn non disponible sur ce navigateur',
    loginUnsupportedBrowser: 'Votre navigateur ne supporte pas WebAuthn. Utilisez un navigateur moderne (Chrome, Firefox, Safari, Edge).',
    loginButton: 'Se connecter avec WebAuthn',
    loginButtonLoading: 'Connexion…',
    loginLostDevice: "J'ai perdu mon appareil",
    loginLostDeviceTitle: "Perte d'appareil",
    loginNoAccount: "Pas encore de compte ? S'inscrire",
    loginRegisterNewDevice: 'Enregistrer un nouvel appareil (workflow complet)',
    loginBackToLogin: 'Retour à la connexion normale',
    registerTitle: 'Créer un compte',
    registerSubtitle: 'Authentification sécurisée avec WebAuthn',
    registerUnsupportedBrowserTitle: 'Navigateur non compatible',
    registerUnsupportedBrowser: 'Votre navigateur ne supporte pas WebAuthn. Utilisez un navigateur moderne (Chrome, Firefox, Safari, Edge).',
    registerEmailLabel: 'Email',
    registerGetCode: 'Obtenir un code',
    registerSendingCode: 'Envoi…',
    registerAlreadyHaveAccount: 'Déjà un compte ? Se connecter',
    registerCodeLabel: 'Code à 6 chiffres',
    registerCodeHelp: 'Saisissez le code reçu par email',
    registerVerifyCode: 'Vérifier le code',
    registerVerifyingCode: 'Vérification…',
    registerChangeEmail: "Modifier l'email",
    registerCodeVerifiedTitle: 'Code vérifié !',
    registerPasskeyButton: 'Enregistrer mon appareil WebAuthn',
    registerRegistering: 'Enregistrement…',
    registerSuccessTitle: 'Inscription réussie !',
    registerSuccessCodeSent: 'Code envoyé par email',
    registerSuccessRedirecting: 'Inscription réussie ! Redirection…',
    registerErrorInvalidEmail: 'Veuillez saisir une adresse email valide',
    registerErrorSendCode: "Erreur lors de l'envoi du code",
    magicLinkTitle: 'Vérification du lien magique',
    magicLinkVerifying: 'Vérification en cours…',
    magicLinkSuccess: 'Vous êtes connecté.',
    magicLinkSuccessTitle: 'Connexion réussie !',
    magicLinkErrorTitle: 'Erreur de vérification',
    magicLinkBackToLogin: 'Retour à la connexion',
    magicLinkErrorMissingToken: 'Token manquant dans l\'URL',
    magicLinkErrorVerifyFailed: 'Erreur lors de la vérification du lien magique',
    devicesTitle: 'Mes appareils',
    devicesSubtitle: "Gérez les appareils enregistrés pour l'authentification WebAuthn",
    devicesEmpty: 'Aucun appareil enregistré',
    devicesRegister: 'Enregistrer un appareil',
    devicesAddNew: 'Ajouter un nouvel appareil',
    devicesRename: 'Renommer',
    devicesRevoke: 'Révoquer',
    devicesUvEnabled: 'UV activée',
    devicesAddedOn: 'Ajouté le {date}',
    devicesLastUsed: 'Dernière utilisation : {date}',
    devicesConfirmRevoke: 'Êtes-vous sûr de vouloir révoquer l\'appareil "{deviceName}" ? Vous ne pourrez plus vous connecter avec cet appareil.',
    devicesErrorLoad: 'Erreur lors du chargement des appareils',
    devicesErrorUpdate: 'Erreur lors de la mise à jour',
    devicesErrorRevoke: 'Erreur lors de la révocation',
    devicePairTitle: 'Appairer un appareil',
    devicePairSubtitle: "Saisissez le code affiché par l'application compagnon sur votre poste de travail.",
    devicePairCodeLabel: "Code d'appairage",
    devicePairCodePlaceholder: 'PAIR-XXXX',
    devicePairDeviceNameLabel: "Nom de l'appareil",
    devicePairDeviceNamePlaceholder: 'Mon poste de travail',
    devicePairConfirm: "Appairer l'appareil",
    devicePairConfirming: 'Appairage…',
    devicePairSuccess: 'Appareil appairé. Vous pouvez retourner à l\'application sur votre poste de travail.',
    devicePairBack: 'Retour aux appareils',
    devicePairErrorCodeRequired: "Le code d'appairage est requis.",
    devicePairErrorNotFound: 'Code invalide ou expiré.',
    devicePairErrorGeneric: "Échec de l'appairage de l'appareil.",
    passkeyRegistrationCancelled: "Vous avez annulé l'inscription",
    passkeyAuthenticationCancelled: "Vous avez annulé l'authentification",
    passkeyAlreadyRegistered: 'Cet appareil est déjà enregistré',
    passkeyNoMatchingAuthenticator: 'Aucun appareil reconnu',
    passkeyAuthenticatorNotSupported: "Cet authentificateur n'est pas supporté",
    ...overrides,
  });

export const createDefaultAuthUiBranding = (overrides: Partial<AuthUiBranding> = {}): AuthUiBranding => {
  const branding: AuthUiBranding = {
    primaryColor: '#4f46e5',
    accentColor: '#0f766e',
    ...overrides,
  };

  if (branding.productName && !branding.logoAlt) {
    branding.logoAlt = branding.productName;
  }

  return branding;
};
