#!/usr/bin/env bash
# harness — host shim for the @sentropic/harness CLI (BR-42h Lot 6).
# Docker-first: the engine runs in a container; no node/npm on the host.
# Generated by `make install-harness-cli` — do not edit in place; reinstall instead.
set -euo pipefail

REPO="@HARNESS_REPO@"
DIST="$REPO/packages/harness/dist/bin/harness.js"

if [ ! -f "$DIST" ]; then
  echo "harness: dist missing — building once via make build-harness..." >&2
  make -C "$REPO" build-harness >/dev/null
fi

# CWD is mounted at /workdir so relative paths (e.g. --branch-md BRANCH.md)
# resolve against where the user runs the command. Repo mounted read-only.
exec docker run --rm -u "$(id -u):$(id -g)" -e HOME=/tmp \
  -v "$REPO:/repo:ro" -v "$PWD:/workdir" -w /workdir \
  node:24-bookworm-slim node /repo/packages/harness/dist/bin/harness.js "$@"
