import { createHash } from 'node:crypto';
import { readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';

const root = process.cwd();
const inputPath = resolve(root, 'scripts/llm-model-equivalences/council.source.json');
const outputPath = resolve(root, 'packages/llm-mesh/src/generated-model-council.ts');
const source = JSON.parse(await readFile(inputPath, 'utf8'));
const normalized = {
  revision: source.revision,
  expiresAt: source.expiresAt,
  reason: source.reason,
  reviewer: source.reviewer,
  provenance: source.provenance,
  excludedModelKeys: [...source.excludedModelKeys].sort(),
};
const canonical = JSON.stringify(normalized);
const digest = createHash('sha256').update(canonical).digest('hex');
const quote = (value) => JSON.stringify(value);
const generated = [
  '// Generated by make refresh-llm-model-equivalences. Do not edit.',
  'export const GENERATED_MODEL_COUNCIL_SOURCE = {',
  `  revision: ${quote(normalized.revision)},`,
  `  digest: ${quote(`sha256:${digest}`)},`,
  `  expiresAt: ${quote(normalized.expiresAt)},`,
  `  reason: ${quote(normalized.reason)},`,
  `  reviewer: ${quote(normalized.reviewer)},`,
  `  provenance: ${quote(normalized.provenance)},`,
  '  excludedModelKeys: [',
  ...normalized.excludedModelKeys.map((key) => `    ${quote(key)},`),
  '  ],',
  '} as const;',
  '',
].join('\n');

if (process.argv.includes('--check')) {
  const current = await readFile(outputPath, 'utf8').catch(() => '');
  if (current !== generated) {
    throw new Error('Model equivalence council is stale; run make refresh-llm-model-equivalences');
  }
} else {
  await writeFile(outputPath, generated);
}
