apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-api-to-postgres
  namespace: sentropic
  labels:
    app.kubernetes.io/name: sentropic
    app.kubernetes.io/component: postgres
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: sentropic
      app.kubernetes.io/component: postgres
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: sentropic
              app.kubernetes.io/component: api
      ports:
        - protocol: TCP
          port: 5432
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-ui-to-api
  namespace: sentropic
  labels:
    app.kubernetes.io/name: sentropic
    app.kubernetes.io/component: api
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: sentropic
      app.kubernetes.io/component: api
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: sentropic
              app.kubernetes.io/component: ui
      ports:
        - protocol: TCP
          port: 8787
